---
- name: Ensure unzip is installed.
  package: name=unzip state=present

- name: Download and expand sonar-runner.
  unarchive:
    src: "{{ sonar_runner_download_url }}"
    dest: "{{ workspace }}"
    copy: false
    creates: /usr/local/sonar-runner/bin/sonar-runner
  become: true

- name: Move sonar-runner into place.
  command: >
    mv {{ workspace }}/{{ sonar_runner_expanded_file }} /usr/local/sonar-runner
    creates=/usr/local/sonar-runner/bin/sonar-runner

- name: Copy sonar-runner properties into place.
  template:
    src: sonar-runner.properties.j2
    dest: /usr/local/sonar-runner/conf/sonar-runner.properties

- name: Configure sonar-runner bash settings by copying script into profile.d.
  copy:
    src: sonar.sh
    dest: /etc/profile.d/sonar.sh
